Added Liatrio flavicon to dashboard
liatrio/ldop-nginx pull request #3
Opened 2017-07-03 23:04 UTC by HunterMayers

Added a Liatrio flavicon to the ldop dashboard.

2017-07-03 23:09 UTC, ebracho commented
flavicon??

lgtm

2017-07-03 23:10 UTC, ebracho approved these changes

2017-07-03 23:34 UTC, ghost requested changes
This is a fantastic detail! Can we rename the file to something less generic?

2017-07-04 00:32 UTC, HunterMayers commented
Updated name of favicon and matched new image name in index.html

2017-07-04 00:35 UTC, ghost approved these changes

2017-07-04 00:36 UTC, merged